name: vocab-to-anki-app
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - beautifulsoup4
  - requests
  - genanki
  - gtts
  - validators
  - pip:
      - kivy[full]
      - kivymd
      - user_agent