name: vocab-to-anki
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - beautifulsoup4
  - requests
  - genanki
  - gtts
  - validators
  - pip:
      - ibm-watson
      - kivy[full]
      - kivymd
      - lxml
      - pyinstaller[encryption]
      - user_agent